# Generated by Django 3.0 on 2021-12-19 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20211217_1229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='title',
            new_name='name',
        ),
    ]
